"""Initial migration

Revision ID: 87fcc1b2f02b
Revises: cf1bd21e8a6b
Create Date: 2026-07-25 14:40:16.215090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fcc1b2f02b'
down_revision: Union[str, Sequence[str], None] = 'cf1bd21e8a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
