"""meessage

Revision ID: 9cc3226f5a75
Revises: 87fcc1b2f02b
Create Date: 2026-07-27 01:26:42.740410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc3226f5a75'
down_revision: Union[str, Sequence[str], None] = '87fcc1b2f02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraryUsers', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('libraryUsers', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('libraryUsers', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('libraryUsers', 'password')
    # ### end Alembic commands ###
